const {chromium}=require('playwright');
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:360,height:800},deviceScaleFactor:2});
 const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{ if(m.type()==='error') errs.push(m.text()); });
 await p.goto('file://'+__dirname+'/../game/guildhall.html'); await p.waitForTimeout(400);
 await p.click('button[data-a="new"]'); await p.waitForTimeout(150);
 let ps=await p.$$('button[data-pick]'); await ps[0].click(); await p.waitForTimeout(80); ps=await p.$$('button[data-pick]:not([disabled])'); await ps[0].click(); await p.waitForTimeout(200);
 // simulate winning floor 2
 await p.evaluate(()=>{ run.floor=2; run.gold=20; run.heroes[0].gems=['venom','ward']; run.heroes[1].gems=['swift',null,null,'edge']; run.heroes[1].open=[0,1,3]; run.heroes[1].lv=2; run.bag=['frost','bloodstone'];
   run.heroes.push({id:'cleric',lv:1,gems:[],open:[0,1],row:'back'}); offerPaths(); renderCamp(); });
 await p.evaluate(()=>{ run.floor++; run.bonus={opts:['enchanter','cutter']}; offerPaths(); rollShop(false); renderCamp(); });
 await p.waitForTimeout(150); await p.screenshot({path:'ev_camp.png'});
 const shot=async(name,setup)=>{ await p.evaluate(setup); await p.waitForTimeout(150); await (await p.$('#sheet')).screenshot({path:name}); };
 await shot('ev_ench.png',()=>openEnchanter());
 await p.click('[data-en="0"]'); await p.waitForTimeout(80); await p.click('[data-eh="1"]'); await p.waitForTimeout(80); await p.click('[data-en="1"]'); await p.waitForTimeout(80);
 await (await p.$('#sheet')).screenshot({path:'ev_ench2.png'});
 await p.click('[data-ex]'); await p.waitForTimeout(100);
 const fl=await p.evaluate(()=>[run.heroes.map(h=>h.flip),run.bonus, computeStats(run.heroes[0],[]).spikes, run.heroes.map(h=>[0,1,2,3].map(k=>slotKind(k,h)).join(','))]);
 console.log('after enchant',JSON.stringify(fl));
 await p.evaluate(()=>{ run.bonus={opts:['cutter','retire']}; renderCamp(); });
 await shot('ev_cut.png',()=>openCutter());
 await p.click('[data-ci="0"]'); await p.waitForTimeout(80); await (await p.$('#sheet')).screenshot({path:'ev_cut2.png'});
 await p.click('[data-ct="ember"]'); await p.waitForTimeout(80);
 const bagIdx=await p.evaluate(()=>ownedGems().findIndex(x=>x.g==='bloodstone')); await p.click(`[data-ci="${bagIdx}"]`); await p.waitForTimeout(80);
 await (await p.$('#sheet')).screenshot({path:'ev_cut3.png'});
 await p.click('[data-ct="rimeheart"]'); await p.waitForTimeout(150);
 console.log('after cut',JSON.stringify(await p.evaluate(()=>[run.heroes.map(h=>h.gems),run.bag,run.bonus])));
 await p.evaluate(()=>{ run.bonus={opts:['retire','scout']}; renderCamp(); });
 await shot('ev_ret.png',()=>openRetire());
 await p.click('[data-ra="2"]'); await p.waitForTimeout(80); await p.click('[data-rb="0"]'); await p.waitForTimeout(80);
 await (await p.$('#sheet')).screenshot({path:'ev_ret2.png'});
 await p.click('[data-rx="go"]'); await p.waitForTimeout(150);
 console.log('after retire',JSON.stringify(await p.evaluate(()=>[run.heroes.map(h=>[h.id,h.giftHp,h.giftAtk]),run.bag,run.bonus])));
 await p.evaluate(()=>{ run.bonus={opts:['scout','forge']}; renderCamp(); });
 await shot('ev_scout.png',()=>openScout());
 const pick2=await p.evaluate(()=>[...document.querySelectorAll('[data-sb]')].map(x=>x.dataset.sb)); await p.click(`[data-sb="${pick2[1]}"]`); await p.click('[data-sx="go"]'); await p.waitForTimeout(150);
 console.log('after scout',JSON.stringify(await p.evaluate(()=>[run.bosses,actBoss()])));
 // reach boss floor and check encounter normalisation
 await p.evaluate(()=>{ run.floor=4; offerPaths(); renderCamp(); });
 console.log('boss enc',JSON.stringify(await p.evaluate(()=>[run.enc.list[0],run.enc.norm])));
 await p.evaluate(()=>{ run.bonus={opts:['forge','scout']}; run.floor=3; offerPaths(); renderCamp(); });
 await shot('ev_forge.png',()=>openForge());
 await p.click('[data-fg="0"]'); await p.click('[data-fg="1"]'); await p.click('[data-fz="merge"]'); await p.waitForTimeout(150);
 console.log('after forge',JSON.stringify(await p.evaluate(()=>[run.floor,run.bonus,run.heroes.map(h=>h.gems)])));
 await p.screenshot({path:'ev_camp2.png'});
 console.log('errors',errs); await b.close(); })();
