// ---------- codex ----------
function showCodex(tab){
  const tabs=[['h','Heroes'],['g','Gems'],['r','Relics'],['e','Enemies']];
  let body='';
  if(tab==='h') body=[1,2,3].map(t=>`<div class="eyebrow" style="margin-top:6px">${['','Starters (hired)','Tier 3 (first training)','Capstones (second training)'][t]}</div>`+Object.keys(HEROES).filter(id=>HEROES[id].tier===t).map(id=>{ const d=HEROES[id], c=CLASSES[id];
    return `<div class="cx"><div class="t">${ic(id,'h',22)}${esc(d.name)} <span class="tiny muted">${d.row} · ${c.ess.map(e=>GEMS[e].name).join(' + ')} · from ${c.from.map(f=>CLASSES[f].name).join(', ')}</span></div><div class="d">${esc(c.passive)}</div></div>`; }).join('')).join('');
  if(tab==='g') body=`<div class="cx"><div class="d">Each gem gives its passive to the hero holding it. A hero's skills unlock when their slotted gems match the recipe; several can be active at once. Rare gems count as several essences for recipes and give each essence's passive. Slots: 2 at ★, 3 at ★★, 4 at ★★★.</div></div>`+Object.keys(GEMS).filter(id=>!GEMS[id].merged).map(id=>{ const d=GEMS[id]; const s=meta.seen.g.includes(id); const users=Object.keys(HEROES).map(h=>({h,n:CLASSES[h].skills.filter(sk=>sk.need.includes(d.letter)).length})).filter(x=>x.n); return `<div class="cx ${s?'':'unk'}"><div class="t">${s?ic(id,'g',22):''}${s?esc(d.name):'???'} ${d.rare?'<span class="pill g">rare</span>':''}<span class="tiny muted">${d.cost}g</span></div><div class="d">${s?esc(d.desc)+(d.rare?'':'<br><span class="tiny">Used in skills of: '+users.map(x=>HEROES[x.h].name+' ('+x.n+')').join(', ')+'</span>'):'Not yet discovered'}</div></div>`; }).join('');
  if(tab==='r') body=RELIC_TIERS.concat('cursed').flatMap(t=>relicsOfTier(t)).map(id=>{ const d=RELICS[id]; const s=meta.seen.r.includes(id); return `<div class="cx ${s?'':'unk'}"><div class="t">${s?ic(id,'r',22):''}${s?esc(d.name):'???'} ${tierPill(id)} <span class="tiny muted">${d.cost}g</span></div><div class="d">${s?esc(d.desc):'Not yet discovered'}</div></div>`; }).join('');
  if(tab==='e') body=`<div class="cx"><div class="t">Affixes</div><div class="d">From Act 2, enemies may carry one (more often deeper, and at higher depth); Act 2 and 3 elites always do. ${Object.values(AFFIXES).map(A=>`<b style="color:${A.c}">${A.name}</b>: ${esc(A.d)}.`).join(' ')}</div></div>`+Object.keys(ENEMIES).filter(id=>!ENEMIES[id].minion).map(id=>{ const d=ENEMIES[id]; const s=meta.seen.e.includes(id); return `<div class="cx ${s?'':'unk'}"><div class="t">${s?spr(id,22,d.name):''}${s?esc(d.name):'???'} <span class="tiny muted">${s?(d.boss?'boss · ':d.elite?'elite · ':'')+d.row+' · HP '+d.hp+' · ATK '+d.atk+' · SPD '+d.spd+(d.armor?' · ARM '+d.armor:''):''}</span></div><div class="d">${s?esc(d.ab||'No special ability.'):'Not yet encountered'}</div></div>`; }).join('');
  modal(`<div class="row between"><h2>Codex</h2><button class="sm" data-x="close">Close</button></div><div class="tabs">${tabs.map(t=>`<button data-tab="${t[0]}" class="${t[0]===tab?'on':''}">${t[1]}</button>`).join('')}</div><div class="codex">${body}</div>`);
  $('#sheet').onclick=e=>{ const b=e.target.closest('button[data-tab]'); if(b){ showCodex(b.dataset.tab); } if(e.target.closest('button[data-x]')){ $('#sheet').onclick=null; closeModal(); } };
}

