import json,re
from PIL import Image
PAL=json.loads(re.search(r'const SPR_PAL=(\{.*?\});',open('../../game/guildhall.html').read()).group(1))
S={}
S['ratking']="""
........................
..........K.K.K.........
.........KYKYKYK........
...KKK...KYYYYYK...KKK..
..KMMTK.KKKKKKKKK.KTMMK.
..KMTTKKTTTTTTTTTKKTTMK.
...KKTTTTTTTTTTTTTTTKK..
.....KTTXTTTTTTTXTTK....
.....KTTTTTTTTTTTTTK....
......KTTTTKKKTTTTK.....
......KtTTTKMKTTTtK.....
.......KtTTWKWTTtK......
.....KKKKtttttttKKKK....
....KrrRRKttttttKRRrrK..
...KrrRRRKTTTTTTKRRRrrK.
...KrRRRKTTTTTTTTKRRRrK.
..Y.KRRRKTTTTTTTTKRRRK..
.YMY.KRRKTTTTTTTTKRRK...
..Y.KRRRKtTTTTTTtKRRRK..
..T.KRRRRKttttttKRRRRK..
..T..KRRRKTKKKKTKRRRK.MM
..T..KKKKKTK..KTKKKKKMM.
..T.....KKKK..KKKK.MMM..
........................
"""
S['broodmother']="""
........................
........................
..g..................g..
..g......KKKKK.......g..
...g...KKppppPKK....g...
...g..KppPPppppPK...g...
....gKpppPPPpppppK.g....
....gKpppppDppDpppKg....
.gg..KpppppppppppK..gg..
...gggKpppDpppDpppKgg...
.......KpppppppppK......
..g...KKKpppppppKKK...g.
.g..gg.KXXKpppKXXK.gg..g
.g.g...KXXKKKKKXXK...g.g
g..g...KKKpppppKKK...g..
g..g....KppPPPppK....g..
...g...KppPLLPPppK...g..
..g...KpppPLLPPpppK...g.
..g...KppPPPPPPpppK...g.
.g.....KppPPPPpppK.....g
.g......KKpppppKK......g
g.........KKKKK.........
g.......................
........................
"""
S['vampirelord']="""
........................
.........KKKKKK.........
........KHHHHHHK........
.......KHHHHHHHHK.......
.......KHWWWWWWHK.......
.......KWWWWWWWWK.......
.......KWXWWWWXWK.......
.......KWWWWWWWWK.......
........KWWKKWWK........
..KK.....KWWWWK.....KK..
..KrK...KKKWWKKK...KrK..
..KrrKKKRRKWWKRRKKKrrK..
..KrrrKHRRWWWWRRHKrrrK..
..KrrrKHHRRWWRRHHKrrrK..
..KrrrKHHHRRRRHHHKrrrK..
..KrrrKHHHHYYHHHHKrrrK..
..KrrrKHHHHHHHHHHKrrrK..
..KrrrKWKHHHHHHKWKrrrK..
..KrrrrKKHHHHHHKKrrrrK..
..KrrrrrKHHHHHHKrrrrrK..
..KrrrrrKHHKKHHKrrrrrK..
...KrrrrKHHK.KHHKrrrK...
....KKKKKKKK.KKKKKKK....
........................
"""
S['banshee']="""
........................
.........KKKKKK.........
.......KKUUUUUUKK.......
......KUUUUUUUUUUK......
.....KUUKCCCCCCKUUK.....
.....KUKCWWWWWWCKUK.....
....KUUKWKWWWWKWKUUK....
....KUUKWWWWWWWWKUUK....
....KUUKWWWKKWWWKUUK....
...KUUUUKWWKKWWKUUUUK...
...KUUUCCKWWWWKCCUUUK...
..KUUUCCCCKKKKCCCCUUUK..
..KUUCCCCCCCCCCCCCCUUK..
..KUCCWKCCCCCCCCKWCCUK..
..KUCWWKCCCCCCCCKWWCUK..
...KCWK.KCCCCCCK.KWCK...
...KCK..KCCCCCCK..KCK...
....K...KCCcCCcCK..K....
........KCCCcCCcK.......
.......KCCcCCCcCCK......
.......KCcCCKCCcCK......
......KCCcKK.KcCCK......
......KKcK....KKcKK.....
.......KK.......KK......
"""
S['pitlord']="""
..K..................K..
.KXK................KXK.
.KXK......KKKK......KXK.
..KEK...KKRRRRKK...KEK..
..KEEK.KRRRRRRRRK.KEEK..
...KEEKRRRRRRRRRRKEEK...
....KKRRYRRRRRRYRRKK....
.....KRRRYRRRRYRRRK.....
.....KRRRRRRRRRRRRK.....
......KRRRKKKKRRRK......
......KRRKWKKWKRRK......
...KKKKKRRRRRRRRKKKKK...
..KRRRRKrRRRRRRrKRRRRK..
.KRRRRRKrrRRRRrrKRRRRRK.
.KRRKRRKrrrRRrrrKRRKRRK.
.KRK.KRKKrrrrrrKKRK.KRK.
.KRK.KRKOOKKKKOOKRK.KRK.
.KOK..KKrrrrrrrrKK..KOK.
KOYOK.KrrrrrrrrrrK.KOYOK
.KOK..KrrrKKKKrrrK..KOK.
......KrrK....KrrK......
.....KKrrK....KrrKK.....
.....KXXXK....KXXXK.....
.....KKKKK....KKKKK.....
"""
for k,v in S.items():
    rows=[r for r in v.strip('\n').split('\n')]
    assert len(rows)==24,(k,len(rows))
    for i,r in enumerate(rows): assert len(r)==24,(k,i,len(r),r)
    for r in rows:
        for c in r: assert c=='.' or c in PAL,(k,c)
json.dump({k:v.strip('\n').split('\n') for k,v in S.items()},open('new.json','w'))
# preview: existing boss + new ones, 8x
cur=json.loads('{'+','.join(m.group(0) for m in re.finditer(r'"?(goblinking|lich|rifttitan|bonedragon)"?:\[[^\]]*\]', open('../../game/guildhall.html').read()))+'}'.replace('goblinking:','"goblinking":').replace('lich:','"lich":').replace('rifttitan:','"rifttitan":').replace('bonedragon:','"bonedragon":')) if False else {}
allg={k:v.strip('\n').split('\n') for k,v in S.items()}
sc=8; W=len(allg)*(24*sc+16)+16
im=Image.new('RGB',(W,24*sc+32),(20,17,38))
for n,(k,g) in enumerate(allg.items()):
    ox=16+n*(24*sc+16)
    for y,r in enumerate(g):
        for x,c in enumerate(r):
            if c!='.':
                col=PAL[c]; rgb=tuple(int(col[i:i+2],16) for i in (1,3,5))
                for dy in range(sc):
                    for dx in range(sc): im.putpixel((ox+x*sc+dx,16+y*sc+dy),rgb)
im.save('placeholder-preview.png'); print('ok')
