# Guildhall pixel sprites. One char = one pixel. '.' = transparent.
# Heroes face right, enemies face left.

PALETTE = {
 'K':'#1b1530',  # outline
 'S':'#f1c9a5','s':'#c98f66',  # skin
 'W':'#f7f3ea','w':'#c9c4bd',  # white / light gray
 'G':'#8d90a8','g':'#575a75',  # steel
 'R':'#d94a5a','r':'#8e2b3c',  # red
 'O':'#ff9a4d','o':'#c95a1d',  # orange
 'Y':'#f2c14e','y':'#b3832a',  # gold
 'B':'#4f7fd9','b':'#2f4a8f',  # blue
 'C':'#7fc8ff','c':'#3d86c9',  # ice
 'U':'#d6ecff',                # pale ice
 'P':'#9b6fe0','p':'#5a3d99',  # purple
 'N':'#4faa5e','n':'#2d6b3a',  # green
 'L':'#9be15d','l':'#5f9a2d',  # lime / poison
 'T':'#a06a3c','t':'#6b4324',  # brown
 'M':'#ff6b81','m':'#b53f57',  # pink / imp red
 'E':'#e8e0c8','e':'#a89f84',  # bone
 'V':'#7a9a3a','v':'#4a6323',  # goblin green
 'H':'#3b3450','h':'#262138',  # dark cloth
 'D':'#d9b3ff','d':'#8a6fc0',  # wraith lavender
 'Q':'#5ee0c8','q':'#2e9a86',  # teal
 'X':'#ff4b3e',                # glowing red eye
 'I':'#c9a061','i':'#8f6a3a',  # ochre (ogre)
 'A':'#9a9a9a','a':'#5c5c66',  # stone
}

HEROES = {
'sentinel': ("Sentinel", """
..W..KKKKKK.....
..W.KGGGGGGK....
..W.KGGwGGGK....
..W.KGKKKKKK....
..W.KGGGGGGK....
.KYK.KGGGGK.....
..T.KKGGGGKKK...
..TKGKgGGgKYYK..
...KGKgGGgKYYYK.
...KGKgGGgKYYYK.
....KgKgGGgKYYK.
.....KKgGgKKKK..
......KgKKgK....
......KgK.KgK...
.....KKKK.KKKK..
................
"""),
'berserker': ("Berserker", """
....KKKKK.......
...KOOOOOK..KGK.
..KOOOOOOOK.KGGK
..KOOSSSSOKKKGGK
..KOSKSSKSK.TGGK
...KSSSSSK..TGK.
...KsSRRsK..TK..
..KKSSSSSKK.T...
.KSKSRRSSKSKT...
.KSKSSRRSKKTT...
.KsKSSSSSKsKT...
..KKTTTTTKKKT...
...KtTKKtTK.T...
...KtK..KtK.K...
..KKKK..KKKK....
................
"""),
'thief': ("Thief", """
................
.....KKKKK......
....KHHHHHK.....
...KHHHHHHHK....
...KHKhhhhhK....
...KHhSSSShK....
...KHhSKSKhK....
....KhHHHHK.....
...KKHHHHHKK....
..KSKhHHHhKSK...
.KWKHhHHHhHKWK..
.KWK.KhHHhK.KWK.
..K..KTTTTK..K..
.....KhKKhK.....
.....KhK.KhK....
....KKKK.KKKK...
"""),
'shieldmaiden': ("Shieldmaiden", """
..K.............
..KW............
..KW.KKKKKK.....
..T.KGGGGGGK....
..T.KGGGGGGK....
..T.KYSSSSYK....
..T.KYSKSKYK....
..T.KYsSSsYK....
..TKKYKSSKYKKK..
..TKBKBBBBKBBK..
..TKSKBBBBKGGGK.
..TKSKBBBBKGWGK.
...KKKTTTTKGGGK.
.....KbKKbKKKK..
.....KbK.KbK....
....KKKK.KKKK...
"""),
'windrunner': ("Windrunner", """
................
.....KKKKK......
....KNNNNNK.....
...KNNNNNNNK....
...KNKSSSSNK....
...KNSSKSKNK....
....KSsSSsK...K.
...KKNNNNNKK.KIK
..KSKnNNNnKSKIW.
..KsKnNNNnKsKIW.
..K.KnNNNnKKKIW.
....KKTTTTK.KIK.
.....KtKKtK...K.
.....KtK.KtK....
....KKKK.KKKK...
................
"""),
'apothecary': ("Apothecary", """
................
.....KKKKKK.....
....KTTTTTTK....
..KKKtTTTTtKKK..
..KTTTTTTTTTTK..
...KKSSSSSSKK...
....KSKWKWKK....
....KSSsSSsK....
...KKPPPPPPKK...
..KSKpPPPPpKSK..
..KLKpPPPPpKLK..
..KLK.KPPPKKLK..
..KK..KTTTTKKK..
......KpKKpK....
......KpK.KpK...
.....KKKK.KKKK..
"""),
'firemage': ("Fire Mage", """
........K.......
.......KRK......
......KRRRK.....
.....KRRRRRK.K..
....KRRRRRRRKOK.
..KKKKKKKKKKKOYK
....KSSSSSK.KOYK
....KSKSKSK.KYYK
.....KSsSK..KOOK
....KKRRRKK.KSK.
...KRKRrrRKKSK..
...KRKRRrRKRK...
...KRKRrrRKK....
...KRKRRrRK.....
....KRRRRRK.....
...KKKKKKKKK....
"""),
'healer': ("Healer", """
..KYK...........
.KYYYK..........
..KYK.KKKKK.....
..T..KWWWWWK....
..T..KWSSSWK....
..T..KWSKSKK....
..T...KSSSK.....
..TKKKWWWWWKK...
..TKSKWYWYWKSK..
..TKWKWWWWWKWK..
..T.KKWWYWWKK...
.....KWWWWWK....
.....KWWYWWK....
.....KWWWWWK....
....KWWWWWWWK...
....KKKKKKKKK...
"""),
'monk': ("Monk", """
................
.....KKKKK......
....KSSSSSK.....
....KSSSSSK.....
....KSKSSKK.....
....KsSSSsK.....
.....KSSSK......
....KKOOSKK.....
...KSKOOOSKSK...
..KSSKOOOOKSSK..
..KSSKOoOOKSSK..
...KKKOOOOKKK...
.....KTTTTK.....
.....KoKKoK.....
.....KoK.KoK....
....KKKK.KKKK...
"""),
'bountyhunter': ("Bounty Hunter", """
................
....KKKKKKK.....
...KggggggggK...
..KKKKKKKKKKKK..
....KSSSSSK.....
....KSKSKKK.....
.....KSSSK......
....KKggggKK.KK.
...KgKggggKSKTK.
...KgKggggKKTTTK
...KgKggggKSKTK.
....KKggggKK.KK.
.....KgKKgK.....
.....KgK.KgK....
....KKKK.KKKK...
................
"""),
'hearthguard': ("Hearthguard", """
....K.....K.....
....KK...KK.....
....KHKKKHK.....
....KHHHHHK.....
....KHOHOHK.....
....KHHHHHK.....
.....KHHHK......
...KKKHOHKKK....
..KHKHHOHHKHK...
..KOKHOHHOKOK...
..KHKHHOHHKHK...
...KKHHOHHKK....
.....KhKKhK.....
.....KOK.KOK....
.....KhK.KhK....
....KKKK.KKKK...
"""),
'glacierwarden': ("Glacier Warden", """
................
....KKKKKK......
...KCCCCCCK.....
...KCCCCCCK.....
...KCKKKKCK.....
...KCCKKCCK.....
....KCCCCK.KKKK.
...KKCCCCKKKUUUK
..KCKcCCcKcKUCUK
..KCKcCCcKcKUUUK
..KcKcCCcKKKUCUK
...KKcCCcK.KUUUK
.....KcKKcK.KKKK
.....KcK.KcK....
.....KcK.KcK....
....KKKK.KKKK...
"""),
'duelist': ("Duelist", """
..........KMK...
.....KKKKKKMK...
....KbbbbbbKK...
...KKKKKKKKKK...
....KSSSSSK.....
....KSKSKSK.....
.....KSsSK......
....KKBBBBKK....
...KBKBWWBKSK...
...KBKBBBBKSKWWW
...KSKBWWBKK....
....KKBBBBK.....
.....KwKKwK.....
.....KwK.KwK....
.....KwK.KwK....
....KKKK.KKKK...
"""),
'bloodmage': ("Blood Mage", """
................
.....KKKKK......
....KHHHHHK.....
...KHHwwwHHK....
...KHwwKwKHK....
....KwwRwwK.....
.....KwwwK...KK.
....KKRRRRK.KRRK
...KRKRrrRKKRMRK
...KRKRRrRKwKRRK
...KRKRrrRKK.KK.
...KRKRRrRK.....
....KKRrrRK.....
.....KRRRRK.....
....KRRRRRRK....
....KKKKKKKK....
"""),
'plaguedoctor': ("Plague Doctor", """
................
.....KKKKKK.....
....KHHHHHHK....
..KKKKKKKKKKKK..
....KEEEEEEK....
....KEKEEKEK....
....KEEEEEEEKK..
.....KEEEEEEEEK.
.....KKEEEEKKK..
....KKHHHHKK....
...KHKHHHHKHK...
...KTKHHHHKTK...
...KLKHHHHKK....
....KKHHHHK.....
.....KHHHHK.....
....KKKKKKKK....
"""),
'bard': ("Bard", """
.......KKK.K....
.....KKMMMKYK...
....KMMMMMMKK...
....KKKKKKKK....
....KSSSSSK.....
....KSKSKSK.....
.....KSSSK......
....KKNNNNK.....
...KNKNNNNKSKKK.
...KSKNNNNKKTTTK
...KSKNNNNKKTWTK
....KKNNNNK.KTTK
.....KnKKnK..KK.
.....KnK.KnK....
.....KnK.KnK....
....KKKK.KKKK...
"""),
'frostmage': ("Frost Mage", """
..KCK...........
.KCUCK..........
..KCK.KKKKK.....
..T..KWWWWWK....
..T..KWSSSWK....
..T..KWSKSKK....
..T...KSsSK.....
..TKKKUUUUUKK...
..TKSKUCUCUKSK..
..TKUKUUUUUKUK..
..T.KKUUCUUKK...
.....KUUUUUK....
.....KUCUCUK....
.....KUUUUUK....
....KUUUUUUUK...
....KKKKKKKKK...
"""),
'reaper': ("Reaper", """
.............KKK
.....KKKKK..KWWK
....KHHHHHK.KWKK
...KHHHHHHHKKWK.
...KHKEEEEHKKWK.
...KHEKEKEHK.T..
....KEEKEEK..T..
...KKHHHHHKK.T..
..KEKhHHHhKEKT..
..KEKhHHHhKKKT..
..K.KhHHHhK..T..
....KhHHHhK..T..
....KhHHHhK..T..
....KhHHHhK..T..
...KhhHHHhhK.T..
...KKKKKKKKK.K..
"""),
}

ENEMIES = {
'goblin': ("Goblin", """
................
................
................
.....KKKKKK.KK..
....KVVVVVVKVVK.
...KVVXVVVVVVVK.
...KVVVVVKVVVK..
....KVKWWKVVVK..
.....KKVVVKK....
...KGKKVVVKKK...
...KGKVKVVVKVK..
...KKKVKVVVKVK..
.....KKTTTTKK...
......KvKKvK....
......KvK.KvK...
.....KKKK.KKKK..
"""),
'archer': ("Goblin Archer", """
................
................
......KKKKK.....
.....KtttttK....
....KttttttKK...
...KtKVXVVtttK..
...KtVVVVVttK...
....KVVKVVKK....
.I...KKVVVKK....
.IW.KKKVVVKKK...
.IWKVKKtttKKVK..
.IWKKKKtttKKK...
.I...KKtttKK....
.....KvKKKvK....
.....KvK..KvK...
....KKKK..KKKK..
"""),
'spider': ("Cave Spider", """
................
................
................
..g..........g..
..g..KKKKKK..g..
.g.g.KpPPppK.g.g
.g.ggKppPppKgg.g
g..ggKpppppKgg..
g.ggXpppPppppgg.
gggXKpppppppK.gg
g.gggKpppppKggg.
.g.g.KKpppKK.g.g
.g.g..KKKKK.g.g.
..g..........g..
..g..........g..
................
"""),
'wolf': ("Warg", """
................
................
................
................
....K...........
...KgK..........
..KgggKKKKKKKK..
.KgXggggGGGGggK.
.KggggKgGGGGggKK
.KWKKgggGGGGgggK
..KKKKgggGGGGgK.
....KgggggggggK.
....KgKKgKKgKgK.
....KgK.KgKKgKK.
...KKgK.KgK.KgK.
...KKKK.KKK.KKK.
"""),
'shaman': ("Shaman", """
....K.K.K.......
...KRKYKRK......
.KK.KTTTTTK.KK..
KEEKKVVXVVVKKVVK
KEKEKVVVVVVKVVK.
.KKKKVVKKVVVVK..
..T.KKPPPPPKK...
..T.KVKPPPPKVK..
..TKKVKPpPPKVK..
..TKVKKPPPPKK...
..T.KKKPpPPK....
..T...KPPPPK....
..T...KPPPPK....
..T..KPPPPPPK...
..T..KKKKKKKK...
................
"""),
'orc': ("Orc", """
................
......KKKKKK....
.....KvvvvvvK...
....KVVXVVVVVK..
....KVVVVVVVVK..
....KVKKVVVKVK..
....KWKVVVVVK...
...KKKKVVVKKKK..
..KTKVVVVVVKKVK.
.KGKTKVVVVVVKVK.
.KGKTKVVVVVVKVK.
.KGKKKVVVVVVKKK.
..K..KKTTTTTKK..
......KvKKKvK...
......KvK.KvK...
.....KKKK.KKKK..
"""),
'skeleton': ("Skeleton", """
................
......KKKKK.....
.....KEEEEEK....
.....KEKEKEK....
.....KEEEEEK....
......KEKEKK....
.....KKEEEKK....
..K.KEKEeEeKEK..
.KGKEKeEeEeKKEK.
.KGK.KEeEeEK.E..
.KGK..KEEEK..K..
..K..KKEKEKK....
.....KEK.KEK....
.....KEK.KEK....
.....KEK.KEK....
....KKKK.KKKK...
"""),
'imp': ("Imp", """
................
................
................
....K...K.......
....KK.KK.......
....KMMMMK..KK..
...KMXMMMMKKMMK.
...KMMMMMKMMMK..
....KMKKMMMMMK..
.KK..KKMMMKKK...
KOOK.KMMMMMK....
KOYKKMKMMMKMK...
.KKKmKMMMMMKmK..
.....KKmKmKK.K..
......KmKKmK.K..
.....KKKK.KKKKK.
"""),
'troll': ("Troll", """
................
.....KKKKKKK....
....KnnnnnnnK...
...KnnXnnnnnnK..
..KnnKnnnnnnnK..
..KnKKnnnnnnnK..
...KWWKnnnnnKK..
..KKKKnnnnnnKKK.
.KnKnnnNNNnnKnKK
.KnKnnNNNNNnKnKT
.KnKnnNNNNNnKnKT
.KnKnnnNNNnnKKKT
..KKKnnnnnnnKTTT
.....KnKKKnKKTTK
.....KnK.KnK.KK.
....KKKK.KKKK...
"""),
'wraith': ("Wraith", """
................
......KKKKK.....
.....KHHHHHK....
....KHHHHHHHK...
....KHCHCHHHK...
....KHHHHHHHK...
.....KDDDDDK....
....KDKDDDDDKK..
...KDK.DDDDDDDK.
..KDDK.DDDDDDK..
..KK..KDDDDDDK..
......KdDDDdDK..
.....KdKDdDKdK..
.....KK.KdK.KK..
........KK......
................
"""),
'bandit': ("Bandit", """
................
......KKKKK.....
.....KHHHHHK....
.....KSKSSSK....
.....KRRRRRK....
.....KRRRRRKK...
......KSSSK.....
....KKKTTTKKK...
..KGKSKTtTTKSK..
.KGK.KKTTTTKKK..
.KK..KKTtTTK....
......KTTTTK....
.....KKhKKhK....
.....KhK.KhK....
.....KhK.KhK....
....KKKK.KKKK...
"""),
'cultist': ("Cultist", """
................
......KKKKK.....
.....KpppppK....
....KppppppK....
....KpKhhhhpK...
....KpXhXhhpK...
.....KhhhhpK....
....KKpppppKK...
...KRKpPpppKKK..
...KRK.pppppKSK.
...KKKKpPpppKKK.
......KpppppK...
......KpPpppK...
......KpppppK...
.....KppppppK...
.....KKKKKKKK...
"""),
'ogre': ("Ogre", """
........................
........KKKKKKKK........
.......KttttttttK.......
......KIIIIIIIIIIK......
.....KIIXIIIIIIIIK......
.....KIIIIIIIIIIIIK.....
.....KIKKIIIIIIIIIK.....
.....KIIIIIIIIIIIIK.....
......KWWKIIIIIIIK......
.....KKKKKIIIIIIKKK.....
....KIIKIIIIIIIIKIIK....
...KIIKIIIIIIIIIIKIIK...
..KIIKIIIIiIIiIIIIKIIK..
..KIIKIIIiIIIIiIIIKIIKK.
..KIIKIIiIIIIIIiIIKIIKTK
..KIKKIIIIIIIIIIIIKKIKTK
..KKKKIIiIIIIIIiIIKKKTTK
.....KIIIiIIIIiIIIKKTTTK
.....KKtttttttttttKTTTTK
......KtttttttttttKTTTK.
......KiiKKKKKKKiiKKKKK.
......KiiK.....KiiK.....
.....KKiiK.....KiiKK....
.....KKKKK.....KKKKK....
"""),
'hydra': ("Hydra", """
........KKK.............
.......KNNNK...KKK......
......KNXNNK..KNNNK.....
.....KNNNNKK.KNXNNK.....
.....KKKNNK..KNNNKK.....
......KNNK...KKNNK......
.KKK..KNNK....KNNK......
KNNNK.KNNNK..KNNNK......
KNXNNK.KNNNKKNNNK.......
KKNNNK..KNNNNNNNK.......
.KKNNK..KNnNNNNNNK......
..KNNK.KNNNNNNNNNNK.....
...KNNKNNnNNNNNnNNNK....
....KNNNNNNNnNNNNNNNK...
.....KNNnNNNNNNNNNNNNK..
.....KNNNNNNnNNNNNNNNNK.
.....KNnNNNNNNNNnNNNNNK.
......KNNNNNNNNNNNNNNNK.
......KKNNKKKNNNNNNNNNK.
.......KNNK.KNNKKNNNNKK.
.......KNNK.KNNK.KNNNK..
......KKNNK.KNNK..KNNNK.
......KKKKK.KKKK...KKKKK
........................
"""),
'goblinking': ("Goblin King", """
........K..K..K.........
........KYKYKYK.........
........KYYYYYK.........
.......KKKKKKKKK........
......KVVVVVVVVVKKK.....
.....KVVXVVVVVVVKVVK....
.....KVVVVVVVVVVKVVK....
.....KVVVVVKKVVVKVK.....
......KVKWWWKVVVKK......
.......KKVVVVKK.........
..KYK.KKKRRRRKKKRR......
..KYK.KVKRRRRRKRRRK.....
..KTKKVKKRRRRRRKRRRK....
..KTKVKKRRRRRRRKRRRK....
..KTKVKKRRRRRRRKRRRK....
..KTKSKKRRRRRRRKRRRK....
..KTKKKKRRRRRRRKRRRK....
..KT.KYYYYYYYYYKRRRK....
..KT.KYYYYYYYYYKRRRK....
..KT.KKvvvKKvvvKKKK.....
..KT..KvvK..KvvK........
..KT..KvvK..KvvK........
..K..KKvvK..KvvKK.......
.....KKKKK..KKKKK.......
"""),
'lich': ("Lich", """
..........K.............
.........KPK............
........KPPPK...........
........KPKPK...........
.........KKK............
.........KKKKKKK........
........KpppppppK.......
.......KpKEEEEEKpK......
.......KpELELEEKpK......
.......KpEEEEEEEpK......
........KEKEKEKEK.......
.........KKEEEKK........
.......KKppPpppKK.......
......KEKpppppppKEK.....
.....KEKKppPpppppKKEK...
.....KEK.KpppppppK.KEK..
.....KK..KppPppppK..KK..
.........KpppppppK......
.........KppPppppK......
.........KpppppppK......
........KppppPppppK.....
........KpppppppppK.....
.......KpppppppppppK....
.......KKKKKKKKKKKKK....
"""),
'rifttitan': ("Stone Titan", """
........................
.......KKKKKKKKK........
......KAAAAAAAAAK.......
......KAAOAAAAOAK.......
......KAaAAAAAAAK.......
......KAAAAaAAAAK.......
.......KKAAAAAKK........
....KKKKKAaAAAKKKKK.....
...KAAAAKAAAAAKAAAAK....
..KAAAAAAKAAAAKAAAAAAK..
..KAaAAAAKAOAAKAAAAaAK..
.KAAAAAAAKAAAAKAAAAAAAK.
.KAAAAAAAKAAOAKAAAAAAAK.
.KAAAaAAAKAAAAKAAAaAAAK.
.KAAAAAAAKKAAKKAAAAAAAK.
.KAAAAAAKKAAAAKKAAAAAAK.
.KKKKKKKKAAAAAAKKKKKKKK.
.......KAAaAAAAAAK......
......KAAAAAAAAAAAK.....
......KAaAAAKKAAAaAK....
......KAAAAAK.KAAAAK....
.....KAAAAAAK.KAAAAAK...
.....KaaaaaaK.KaaaaaaK..
.....KKKKKKKK.KKKKKKKK..
"""),
}

# ---- new enemies (pass 4, not wired into the game yet) ----
NEW_ENEMIES={
'slime': ("Slime", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'rat': ("Giant Rat", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'bat': ("Cave Bat", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'kobold': ("Kobold", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'sporeling': ("Sporeling", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'zombie': ("Zombie", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'ghoul': ("Ghoul", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'gargoyle': ("Gargoyle", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'necromancer': ("Necromancer", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'mimic': ("Mimic", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'darkknight': ("Dark Knight", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'fireelemental': ("Fire Elemental", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'harpy': ("Harpy", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'basilisk': ("Basilisk", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'fiend': ("Fiend", """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""),
'minotaur': ("Minotaur", """
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
"""),
'bonedragon': ("Bone Dragon", """
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
"""),
}
ENEMIES.update(NEW_ENEMIES)

# --- bosses added in game v35 (placeholder grids from the game live in placeholders/, finished art in fixes/) ---
import os as _os0
NEW_BOSSES={'ratking':'Rat King','broodmother':'Broodmother','vampirelord':'Vampire Lord','banshee':'Banshee','pitlord':'Pit Lord'}
for _k,_n in NEW_BOSSES.items():
    ENEMIES[_k]=(_n,open(_os0.path.join(_os0.path.dirname(_os0.path.abspath(__file__)),'placeholders',_k+'.txt')).read())

# --- class sprites added for the class tree (grids live only in fixes/<id>.txt; blank here so the loader below can fill them) ---
NEW_HEROES={'swordsman':'Swordsman','acrobat':'Acrobat','poisoner':'Poisoner',
 'rimecaller':'Rimecaller','flamecaller':'Flamecaller','merchant':'Merchant','mercenary':'Mercenary','plaguecaller':'Plaguecaller','cleric':'Cleric','elementalist':'Elementalist','frostblade':'Frostblade','cutthroat':'Cutthroat',
 'cryomancer':'Cryomancer','pyromancer':'Pyromancer','guildmaster':'Guildmaster','shadowarcher':'Shadow Archer','venomancer':'Venomancer','vampire':'Vampire','bulwark':'Bulwark','blademaster':'Blademaster',
 'prismaticmagus':'Prismatic Magus','phoenix':'Phoenix','lavastrider':'Lava Strider','assassin':'Assassin','champion':'Champion','bladedancer':'Blade Dancer','alchemist':'Alchemist','runeguard':'Runeguard','necromancerhero':'Necromancer','necrodancer':'Necrodancer','paladin':'Paladin','herald':'Herald','silvertongue':'Silver Tongue','heretic':'Heretic','witchdoctor':'Witch Doctor','icemaiden':'Icemaiden','stormdancer':'Storm Dancer','spellblade':'Spellblade','froststalker':'Frost Stalker','flamedancer':'Flame Dancer','firebomber':'Firebomber','nightblade':'Nightblade','bladestorm':'Bladestorm'}
_BLANK='\n'.join(['.'*16]*16)
for _k,_n in NEW_HEROES.items(): HEROES[_k]=(_n,_BLANK)

def parse(s):
    rows=[r for r in s.strip('\n').split('\n')]
    w=max(len(r) for r in rows)
    return [r.ljust(w,'.') for r in rows]

def all_sprites():
    out=[]
    for k,(n,s) in HEROES.items(): out.append((k,n,'hero',parse(s)))
    for k,(n,s) in ENEMIES.items(): out.append((k,n,'new' if k in NEW_ENEMIES else 'enemy',parse(s)))
    return out

# --- overrides: fixes/<id>.txt replaces the grid for that id ---
import os as _os, glob as _glob
for _f in _glob.glob(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)),'fixes','*.txt')):
    _id=_os.path.basename(_f)[:-4]; _g=open(_f).read()
    if _id in HEROES: HEROES[_id]=(HEROES[_id][0],_g)
    elif _id in ENEMIES: ENEMIES[_id]=(ENEMIES[_id][0],_g)
