# Python twin of tools/build.js for machines without node. Keep the two in step.
import json,os,sys
R=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..'); G=os.path.join(R,'game'); S=os.path.join(G,'src')
snap=json.load(open(os.path.join(R,'design/gem-recipe-bench/recipes.json')))
open(os.path.join(S,'data/classes.js'),'w').write('// Generated by tools/build.js from design/gem-recipe-bench/recipes.json. Do not edit: change the bench and rebuild.\nconst CLASS_DATA='+json.dumps(snap,ensure_ascii=False,separators=(',',':'))+';\n')
ENGINE=['engine/core.js','data/gems.js','data/relics.js','data/enemies.js','data/classes.js','engine/classes.js','engine/stats.js','engine/battle.js']
UI=['ui/dom.js','ui/sprites.js','ui/run.js','ui/screens.js','ui/camp.js','ui/forge.js','ui/events.js','ui/gems.js','ui/battle.js','ui/codex.js','ui/boot.js']
r=lambda f:open(os.path.join(S,f)).read()
engine='\n'+''.join(map(r,ENGINE)); ui='\n'+''.join(map(r,UI))
body=r('app.html')+'<script id="engine">'+engine+'</script>\n\n<script id="ui">'+ui+'</script>\n\n</body></html>'
html=r('head.html')+'<style>\n'+r('style.css')+'</style>\n'+body
open(os.path.join(G,'guildhall.html'),'w').write(html); open(os.path.join(G,'engine.js'),'w').write(engine)
sp=os.path.join(G,'Guildhall-standalone.html'); sa=open(sp).read(); open(sp,'w').write(sa[:sa.index('<body>')+6]+html[html.index('<body>')+6:])
tag=lambda f:f'<script src="src/{f}"></script>'
open(os.path.join(G,'dev.html'),'w').write(r('head.html')+'<link rel="stylesheet" href="src/style.css">\n'+r('app.html')+'\n'.join(map(tag,ENGINE+UI))+'\n</body></html>\n')
print('wrote game/guildhall.html, game/engine.js, game/Guildhall-standalone.html and game/dev.html')
